# Generated by Django 6.0.1 on 2026-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localizacao',
            old_name='data_hora',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='animal',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=50),
        ),
    ]
