# Generated by Django 6.0.1 on 2026-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='solicitacao_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='solicitacao_status',
            field=models.CharField(choices=[('NENHUMA', 'Nenhuma'), ('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='NENHUMA', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='solicitacao_tipo',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('ONG', 'ONG'), ('PROTETOR', 'Protetor'), ('COMUM', 'Usuário Comum')], max_length=20, null=True),
        ),
    ]
