# Generated by Django 6.0.1 on 2026-01-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_data_hora_localizacao_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=100),
        ),
    ]
