# Generated by Django 6.0.1 on 2026-02-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_perfil_solicitacao_data_perfil_solicitacao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade_anos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='porte',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('N', 'Não informado')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('N', 'Não informado')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ADOCAO', 'Para adoção'), ('ADOTADO', 'Adotado'), ('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado'), ('TRATAMENTO', 'Em tratamento')], default='DISPONIVEL', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='vacinado',
            field=models.BooleanField(default=False),
        ),
    ]
