# Generated by Django 6.0.1 on 2026-02-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_castrado_animal_historia_animal_idade_anos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ong_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ong_representante_legal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ONG', 'ONG'), ('PROTETOR', 'Protetor'), ('COMUM', 'Usuário Comum')], default='COMUM', max_length=20),
        ),
    ]
