# Generated by Django 6.0.1 on 2026-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_qr_code_alter_animal_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(max_length=50),
        ),
    ]
