# Generated by Django 6.0.1 on 2026-01-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_qr_code_alter_animal_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
    ]
