# Generated by Django 6.0.1 on 2026-03-01 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_perfil_ong_cnpj_perfil_ong_representante_legal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ADOCAO', 'Para adoção'), ('ADOTADO', 'Adotado'), ('PERDIDO', 'Perdido'), ('TRATAMENTO', 'Em tratamento')], default='ADOCAO', max_length=20),
        ),
        migrations.CreateModel(
            name='InteresseAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=120)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTATADO', 'Contatado'), ('FECHADO', 'Fechado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='animals.animal')),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_adocao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatoEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=120)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos_encontro', to='animals.animal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatos_encontro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
