# Generated by Django 6.0.1 on 2026-03-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_aprovacao_data_animal_aprovacao_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='protetor_cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
